### ISSUE TITLE
Basic effect stack reshuffling utilities

### ISSUE THREAD

**Issue by KingoftheHomeless** [haskell-effectful/effectful#117]
You don't have `raiseUnder`, or any generalization thereof (e.g. Polysemy's `insertAt`). Just `raise`, `subsume`, and `inject` (and I don't consider `inject` -- a function that can't be used instead of `raiseUnder` without requiring you to carry a constraint wherever you go -- a valid solution.)

Pardon my french, but that is bonkers. Across all my work with effect systems, these kinds of effect stack reshuffling utility functions have proven _essential_ whenever I experiment with any even remotely zany effect, and are very useful for any regular user as they can be leveraged to e.g. take an existing interpreter and turning it into a reinterpreter.

I recommend you have a few couple of basic `raiseUnder` variants, plus a more ambitious, general-as-possible-while-still-usable function like `insertAt`. Hell, you're free to crib `insertAt`'s implementation if you like. I won't mind (though 9.2 breaking incoherent instances means it no longer generates as nice type errors... oh well.)

If you do introduce `raiseUnder` and friends, don't repeat our mistake: `raiseUnder2` should introduce one effect under the two top effects of the stack, and `raise2Under` should introduce two effects under the top effect of the stack. Not the other way around, like Polysemy does it.

**Comment by arybczak** [comment]
As I mentioned [here](https://github.com/haskell-effectful/effectful/issues/114#issuecomment-1336174882), I have a plan to generalize `inject` so that these use-cases automatically resolve the `Subset` constraint.

> general-as-possible-while-still-usable function like insertAt

Looks like after this generalization `inject` will have the same utility as `insertAt` (perhaps even better since `inject` doesn't need Nat, but maybe `insertAt` also works if you don't provide it).

> I recommend you have a few couple of basic `raiseUnder` variants

My reason for not providing them was that `inject` will eventually be sufficient, but also, IIUC these functions should be needed very rarely, if only because `effectful` is not `polysemy` and the order of effects doesn't matter.

> these kinds of effect stack reshuffling utility functions have proven essential whenever I experiment with any even remotely zany effect

Can you provide examples so that I can better understand this use-case?

**Comment by arybczak** [comment]
Fixed by generalization of `inject`.
